export * from './current-color'
export * from './fixed-color'
export * from './loaders'
// export * as currentColor from './current-color'
// export * as fixedColor from './fixed-color'
// export * as loaders from './loaders'
